const NOW = '2026-04-03T12:00:00+08:00';

export const parks = [
  {
    id: 1,
    code: 'JS-DEMO',
    name: '江苏省设施农业创新示范基地',
    location: '江苏省南京市浦口区',
    description: '平台主园区，承担番茄、黄瓜与水肥协同决策验证。',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 2,
    code: 'NAT-AGRI-A',
    name: '国家农业科技园区 (A区)',
    location: '江苏省南京市江北新区',
    description: '以连栋温室与日光棚为主的示范分区。',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 3,
    code: 'NJ-STRAW',
    name: '南京高架草莓试验站',
    location: '江苏省南京市溧水区',
    description: '聚焦高架草莓精细化调控与科研试验。',
    created_at: NOW,
    updated_at: NOW,
  },
];

export const users = [
  {
    id: 1,
    park_id: 1,
    name: '张秫瑄',
    role: '首席研究员 / 超级管理员',
    avatar: '张',
    phone: '17512573435',
    is_super_admin: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 2,
    park_id: 2,
    name: '李建国',
    role: '温室技术总监',
    avatar: '李',
    phone: '139****1234',
    is_super_admin: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 3,
    park_id: 3,
    name: '王博',
    role: '巡检试验员',
    avatar: '王',
    phone: '150****5678',
    is_super_admin: 0,
    created_at: NOW,
    updated_at: NOW,
  },
];

export const userPreferences = [
  {
    user_id: 1,
    email: 'zhangshuxuan@smart-agri.local',
    title: '首席研究员',
    affiliation: '江苏省设施农业创新示范基地',
    timezone: 'Asia/Shanghai',
    language: 'zh-CN',
    default_scope: '江苏省设施农业创新示范基地',
    start_page: '首页',
    avatar_theme: 'emerald',
    compact_dashboard: 0,
    auto_open_analysis: 1,
    updated_at: NOW,
  },
  {
    user_id: 2,
    email: 'lijianguo@smart-agri.local',
    title: '温室技术总监',
    affiliation: '国家农业科技园区 (A区)',
    timezone: 'Asia/Shanghai',
    language: 'zh-CN',
    default_scope: '国家农业科技园区 (A区)',
    start_page: '棚室管理',
    avatar_theme: 'blue',
    compact_dashboard: 1,
    auto_open_analysis: 1,
    updated_at: NOW,
  },
  {
    user_id: 3,
    email: 'wangbo@smart-agri.local',
    title: '巡检试验员',
    affiliation: '南京高架草莓试验站',
    timezone: 'Asia/Shanghai',
    language: 'zh-CN',
    default_scope: '南京高架草莓试验站',
    start_page: '报警中心',
    avatar_theme: 'amber',
    compact_dashboard: 0,
    auto_open_analysis: 0,
    updated_at: NOW,
  },
];

export const greenhouses = [
  {
    id: 1,
    park_id: 1,
    name: 'A区番茄棚 (连栋)',
    code: 'GH-A-TOM-01',
    zone_name: 'A区',
    crop_name: '番茄',
    growth_stage: '开花坐果期',
    structure_type: '连栋',
    temp: 26.5,
    humidity: 75,
    soil_moisture: 24,
    ec: 2.1,
    status: 'warning',
    online_device_count: 6,
    irrigation_mode: 'assisted',
    last_collected_at: '2026-04-03T10:23:00+08:00',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 2,
    park_id: 1,
    name: 'B区黄瓜棚 (日光)',
    code: 'GH-B-CUC-01',
    zone_name: 'B区',
    crop_name: '黄瓜',
    growth_stage: '结瓜期',
    structure_type: '日光',
    temp: 28,
    humidity: 65,
    soil_moisture: 32,
    ec: 1.8,
    status: 'normal',
    online_device_count: 5,
    irrigation_mode: 'manual',
    last_collected_at: '2026-04-03T09:50:00+08:00',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 3,
    park_id: 3,
    name: 'C区草莓棚 (高架)',
    code: 'GH-C-STR-01',
    zone_name: 'C区',
    crop_name: '草莓',
    growth_stage: '膨大期',
    structure_type: '高架',
    temp: 22.5,
    humidity: 60,
    soil_moisture: 28,
    ec: 1.2,
    status: 'normal',
    online_device_count: 4,
    irrigation_mode: 'manual',
    last_collected_at: '2026-04-03T08:00:00+08:00',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 4,
    park_id: 1,
    name: 'D区育苗棚 (智能玻璃)',
    code: 'GH-D-NRS-01',
    zone_name: 'D区',
    crop_name: '番茄苗',
    growth_stage: '育苗期',
    structure_type: '智能玻璃',
    temp: 24.2,
    humidity: 72,
    soil_moisture: 35,
    ec: 1.5,
    status: 'normal',
    online_device_count: 4,
    irrigation_mode: 'manual',
    last_collected_at: '2026-04-03T09:40:00+08:00',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 5,
    park_id: 1,
    name: 'E区彩椒棚 (连栋)',
    code: 'GH-E-PEP-01',
    zone_name: 'E区',
    crop_name: '彩椒',
    growth_stage: '坐果期',
    structure_type: '连栋',
    temp: 25.8,
    humidity: 68,
    soil_moisture: 29,
    ec: 1.9,
    status: 'normal',
    online_device_count: 4,
    irrigation_mode: 'assisted',
    last_collected_at: '2026-04-03T09:15:00+08:00',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 6,
    park_id: 1,
    name: 'F区叶菜棚 (NFT)',
    code: 'GH-F-LEF-01',
    zone_name: 'F区',
    crop_name: '生菜',
    growth_stage: '采收前',
    structure_type: 'NFT',
    temp: 21.4,
    humidity: 70,
    soil_moisture: 40,
    ec: 1.4,
    status: 'maintenance',
    online_device_count: 3,
    irrigation_mode: 'manual',
    last_collected_at: '2026-04-03T07:40:00+08:00',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 7,
    park_id: 1,
    name: 'G区甜瓜棚 (日光)',
    code: 'GH-G-MEL-01',
    zone_name: 'G区',
    crop_name: '甜瓜',
    growth_stage: '膨果期',
    structure_type: '日光',
    temp: 27.1,
    humidity: 63,
    soil_moisture: 31,
    ec: 1.7,
    status: 'normal',
    online_device_count: 4,
    irrigation_mode: 'manual',
    last_collected_at: '2026-04-03T09:05:00+08:00',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 8,
    park_id: 2,
    name: 'H区番茄棚2号 (连栋)',
    code: 'GH-H-TOM-02',
    zone_name: 'H区',
    crop_name: '番茄',
    growth_stage: '转色期',
    structure_type: '连栋',
    temp: 29.3,
    humidity: 82,
    soil_moisture: 23,
    ec: 2,
    status: 'warning',
    online_device_count: 5,
    irrigation_mode: 'assisted',
    last_collected_at: '2026-04-03T09:58:00+08:00',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 9,
    park_id: 2,
    name: 'I区黄瓜苗棚 (育苗)',
    code: 'GH-I-CUC-02',
    zone_name: 'I区',
    crop_name: '黄瓜苗',
    growth_stage: '育苗期',
    structure_type: '育苗温室',
    temp: 23.9,
    humidity: 74,
    soil_moisture: 34,
    ec: 1.3,
    status: 'normal',
    online_device_count: 3,
    irrigation_mode: 'manual',
    last_collected_at: '2026-04-03T08:35:00+08:00',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 10,
    park_id: 3,
    name: 'J区蓝莓棚 (高架)',
    code: 'GH-J-BLU-01',
    zone_name: 'J区',
    crop_name: '蓝莓',
    growth_stage: '开花期',
    structure_type: '高架',
    temp: 20.6,
    humidity: 58,
    soil_moisture: 27,
    ec: 1.1,
    status: 'offline',
    online_device_count: 0,
    irrigation_mode: 'manual',
    last_collected_at: '2026-04-02T17:10:00+08:00',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 11,
    park_id: 1,
    name: 'K区生菜棚 (水培)',
    code: 'GH-K-LET-01',
    zone_name: 'K区',
    crop_name: '生菜',
    growth_stage: '采收中',
    structure_type: '水培',
    temp: 22.1,
    humidity: 66,
    soil_moisture: 38,
    ec: 1.6,
    status: 'normal',
    online_device_count: 4,
    irrigation_mode: 'manual',
    last_collected_at: '2026-04-03T08:55:00+08:00',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 12,
    park_id: 3,
    name: 'L区草莓棚2号 (高架)',
    code: 'GH-L-STR-02',
    zone_name: 'L区',
    crop_name: '草莓',
    growth_stage: '膨大期',
    structure_type: '高架',
    temp: 23.1,
    humidity: 61,
    soil_moisture: 30,
    ec: 1.3,
    status: 'normal',
    online_device_count: 3,
    irrigation_mode: 'manual',
    last_collected_at: '2026-04-03T08:42:00+08:00',
    created_at: NOW,
    updated_at: NOW,
  },
];

const greenhouseProfileOverrides = {
  1: {
    manager_user_id: 2,
    area_sqm: 1800,
    device_total_count: 6,
    device_online_count: 6,
    irrigation_strategy: '滴灌 + 水肥一体机',
    last_service_at: '2026-04-02T17:20:00+08:00',
    target_temp_min: 22,
    target_temp_max: 28,
    target_humidity_min: 60,
    target_humidity_max: 75,
    target_soil_moisture_min: 26,
    target_soil_moisture_max: 34,
    target_ec_min: 1.8,
    target_ec_max: 2.3,
    notes_json: [
      '夜间高湿需要优先联动顶窗与侧窗除湿。',
      '滴灌阀组建议维持早晚双峰补灌策略。',
    ],
    device_state_json: {
      irrigation: false,
      ventilation: 35,
      nutrientPump: true,
      fillLight: false,
      shadeScreen: 20,
    },
  },
  2: {
    manager_user_id: 2,
    area_sqm: 1200,
    device_total_count: 5,
    device_online_count: 5,
    irrigation_strategy: '脉冲灌溉 + 通风联动',
    last_service_at: '2026-04-03T08:20:00+08:00',
    target_temp_min: 24,
    target_temp_max: 29,
    target_humidity_min: 58,
    target_humidity_max: 72,
    target_soil_moisture_min: 28,
    target_soil_moisture_max: 36,
    target_ec_min: 1.6,
    target_ec_max: 2.0,
    notes_json: [
      '白天蒸腾较强，宜采用短频快补灌。',
      '高温时优先顶侧通风，避免连开湿帘造成病害压力。',
    ],
    device_state_json: {
      irrigation: false,
      ventilation: 35,
      nutrientPump: true,
      fillLight: false,
      shadeScreen: 10,
    },
  },
  3: {
    manager_user_id: 3,
    area_sqm: 950,
    device_total_count: 5,
    device_online_count: 4,
    irrigation_strategy: '营养液循环 + EC 闭环控制',
    last_service_at: '2026-04-03T08:16:00+08:00',
    target_temp_min: 18,
    target_temp_max: 24,
    target_humidity_min: 55,
    target_humidity_max: 68,
    target_soil_moisture_min: 24,
    target_soil_moisture_max: 32,
    target_ec_min: 1.1,
    target_ec_max: 1.5,
    notes_json: [
      '高架草莓对夜间温光联动更敏感。',
      '建议优先保障 EC 传感器冗余。',
    ],
    device_state_json: {
      irrigation: true,
      ventilation: 20,
      nutrientPump: true,
      fillLight: true,
      shadeScreen: 0,
    },
  },
};

function resolveDefaultManagerUserId(greenhouse) {
  if (greenhouse.park_id === 3) {
    return 3;
  }

  return greenhouse.park_id === 2 ? 2 : 1;
}

function buildDefaultTargets(greenhouse) {
  const baseTemp = greenhouse.crop_name.includes('草莓') || greenhouse.crop_name.includes('蓝莓') ? [18, 24] : [22, 29];
  const baseHumidity = greenhouse.crop_name.includes('育苗') ? [68, 80] : [58, 74];
  const baseMoisture = greenhouse.structure_type.includes('水培') || greenhouse.structure_type.includes('NFT') ? [34, 42] : [26, 34];
  const baseEc = greenhouse.crop_name.includes('草莓') || greenhouse.crop_name.includes('蓝莓') ? [1.1, 1.5] : [1.5, 2.2];

  return {
    target_temp_min: baseTemp[0],
    target_temp_max: baseTemp[1],
    target_humidity_min: baseHumidity[0],
    target_humidity_max: baseHumidity[1],
    target_soil_moisture_min: baseMoisture[0],
    target_soil_moisture_max: baseMoisture[1],
    target_ec_min: baseEc[0],
    target_ec_max: baseEc[1],
  };
}

function buildDefaultProfile(greenhouse) {
  return {
    greenhouse_id: greenhouse.id,
    manager_user_id: resolveDefaultManagerUserId(greenhouse),
    area_sqm: 900 + greenhouse.id * 85,
    device_total_count: Math.max(greenhouse.online_device_count, 4),
    device_online_count: greenhouse.online_device_count,
    irrigation_strategy:
      greenhouse.irrigation_mode === 'assisted' ? 'AI辅助补灌 + 传感闭环' : '巡检确认 + 手动灌溉',
    last_service_at: greenhouse.last_collected_at,
    ...buildDefaultTargets(greenhouse),
    notes_json: [
      `${greenhouse.zone_name}${greenhouse.crop_name}棚建议每周完成一次传感器校准。`,
      greenhouse.status === 'warning'
        ? '当前棚室存在异常指标，建议优先关注环境与水肥联动。'
        : '当前棚室运行平稳，可继续沿用现有控制策略。',
    ],
    device_state_json: {
      irrigation: greenhouse.soil_moisture < 26,
      ventilation: greenhouse.humidity > 75 ? 45 : greenhouse.status === 'offline' ? 0 : 20,
      nutrientPump: greenhouse.ec >= 1.2,
      fillLight: greenhouse.structure_type.includes('育苗'),
      shadeScreen: greenhouse.temp > 28 ? 35 : 10,
    },
    updated_at: NOW,
  };
}

export const greenhouseProfiles = greenhouses.map((greenhouse) => {
  const profile = greenhouseProfileOverrides[greenhouse.id];

  if (!profile) {
    return buildDefaultProfile(greenhouse);
  }

  return {
    greenhouse_id: greenhouse.id,
    ...profile,
    updated_at: NOW,
  };
});

const readingOffsets = [
  { recorded_at: '2026-04-03T06:00:00+08:00', temp_delta: -1.1, humidity_delta: 4, soil_delta: 1.8, ec_delta: 0.08, light_lux: 1800, co2_ppm: 560 },
  { recorded_at: '2026-04-03T12:00:00+08:00', temp_delta: 1.5, humidity_delta: -3, soil_delta: -1.2, ec_delta: 0.04, light_lux: 32500, co2_ppm: 430 },
  { recorded_at: '2026-04-03T18:00:00+08:00', temp_delta: 0.4, humidity_delta: 1, soil_delta: -0.6, ec_delta: 0, light_lux: 4200, co2_ppm: 505 },
];

function round(value) {
  return Number(value.toFixed(1));
}

export const sensorReadings = greenhouses.flatMap((greenhouse) =>
  readingOffsets.map((offset, index) => ({
    id: greenhouse.id * 10 + index + 1,
    greenhouse_id: greenhouse.id,
    recorded_at: offset.recorded_at,
    temp: round(greenhouse.temp + offset.temp_delta + greenhouse.id * 0.05),
    humidity: round(greenhouse.humidity + offset.humidity_delta - greenhouse.id * 0.1),
    soil_moisture: round(greenhouse.soil_moisture + offset.soil_delta),
    ec: round(greenhouse.ec + offset.ec_delta),
    light_lux: offset.light_lux + greenhouse.id * 120,
    co2_ppm: offset.co2_ppm + greenhouse.id * 3,
  })),
);

export const decisions = [
  {
    id: 101,
    greenhouse_id: 1,
    type: '灌溉建议',
    action: '开启滴灌 20 分钟',
    confidence: 0.95,
    reason: '基质含水率连续2小时低于25%，且当前光照辐射强，蒸散需求高。',
    status: 'pending',
    created_by: 'ai-engine',
    acted_by_user_id: null,
    acted_at: null,
    created_at: '2026-04-03T10:20:00+08:00',
    updated_at: '2026-04-03T10:20:00+08:00',
  },
  {
    id: 102,
    greenhouse_id: 2,
    type: '环境调控',
    action: '开启顶侧通风，降湿',
    confidence: 0.88,
    reason: '当前湿度88%，且外界温度适宜，通风可有效降低病害风险。',
    status: 'approved',
    created_by: 'ai-engine',
    acted_by_user_id: 2,
    acted_at: '2026-04-03T09:40:00+08:00',
    created_at: '2026-04-03T09:18:00+08:00',
    updated_at: '2026-04-03T09:40:00+08:00',
  },
];

export const alerts = [
  {
    id: 1,
    greenhouse_id: 1,
    type: '环境报警',
    level: '高',
    content: 'A区番茄棚夜间湿度超过85%，灰霉病风险极高',
    status: 'active',
    resolved: 0,
    occurred_at: '2026-04-03T10:23:00+08:00',
    resolved_at: null,
    resolved_by_user_id: null,
    resolution_note: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 2,
    greenhouse_id: 2,
    type: '水肥预警',
    level: '中',
    content: 'B区黄瓜棚基质水分低于阈值(25%)',
    status: 'active',
    resolved: 0,
    occurred_at: '2026-04-03T09:15:00+08:00',
    resolved_at: null,
    resolved_by_user_id: null,
    resolution_note: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 3,
    greenhouse_id: 3,
    type: '设备报警',
    level: '低',
    content: 'C区草莓棚2号土壤EC传感器离线',
    status: 'resolved',
    resolved: 1,
    occurred_at: '2026-04-03T08:00:00+08:00',
    resolved_at: '2026-04-03T08:16:00+08:00',
    resolved_by_user_id: 3,
    resolution_note: '已重启采集网关，EC 传感器恢复在线。',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 4,
    greenhouse_id: 2,
    type: '环境报警',
    level: '中',
    content: 'B区黄瓜棚温度连续2小时高于32℃',
    status: 'resolved',
    resolved: 1,
    occurred_at: '2026-04-02T14:20:00+08:00',
    resolved_at: '2026-04-02T14:48:00+08:00',
    resolved_by_user_id: 2,
    resolution_note: '已调整通风角度并开启湿帘降温。',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 5,
    greenhouse_id: 3,
    type: '水肥预警',
    level: '低',
    content: 'C区草莓棚A液肥罐液位偏低',
    status: 'resolved',
    resolved: 1,
    occurred_at: '2026-04-02T09:00:00+08:00',
    resolved_at: '2026-04-02T09:20:00+08:00',
    resolved_by_user_id: 3,
    resolution_note: '已补充营养液并完成泵站巡检。',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 6,
    greenhouse_id: 1,
    type: '设备报警',
    level: '高',
    content: 'A区番茄棚主水泵电流异常',
    status: 'resolved',
    resolved: 1,
    occurred_at: '2026-04-01T18:30:00+08:00',
    resolved_at: '2026-04-01T19:10:00+08:00',
    resolved_by_user_id: 2,
    resolution_note: '已更换接触器并完成空载测试。',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 7,
    greenhouse_id: 4,
    type: '环境报警',
    level: '中',
    content: 'D区育苗棚夜温低于18℃，存在幼苗僵苗风险',
    status: 'active',
    resolved: 0,
    occurred_at: '2026-04-03T06:45:00+08:00',
    resolved_at: null,
    resolved_by_user_id: null,
    resolution_note: null,
    created_at: NOW,
    updated_at: NOW,
  },
];

export const irrigationEvents = [
  { id: 1, greenhouse_id: 1, decision_id: null, initiated_by_user_id: 2, trigger_source: 'manual', duration_minutes: 18, water_volume_m3: 1.8, started_at: '2026-04-03T06:30:00+08:00', completed_at: '2026-04-03T06:48:00+08:00', notes: '清晨补灌' },
  { id: 2, greenhouse_id: 2, decision_id: null, initiated_by_user_id: 2, trigger_source: 'rule', duration_minutes: 15, water_volume_m3: 1.2, started_at: '2026-04-03T07:10:00+08:00', completed_at: '2026-04-03T07:25:00+08:00', notes: '低阈值自动触发' },
  { id: 3, greenhouse_id: 3, decision_id: null, initiated_by_user_id: 3, trigger_source: 'manual', duration_minutes: 12, water_volume_m3: 0.8, started_at: '2026-04-03T07:40:00+08:00', completed_at: '2026-04-03T07:52:00+08:00', notes: '草莓营养液补给' },
  { id: 4, greenhouse_id: 5, decision_id: null, initiated_by_user_id: 1, trigger_source: 'rule', duration_minutes: 20, water_volume_m3: 1.6, started_at: '2026-04-03T08:15:00+08:00', completed_at: '2026-04-03T08:35:00+08:00', notes: '定时灌溉' },
  { id: 5, greenhouse_id: 7, decision_id: null, initiated_by_user_id: 2, trigger_source: 'manual', duration_minutes: 16, water_volume_m3: 1.1, started_at: '2026-04-03T08:50:00+08:00', completed_at: '2026-04-03T09:06:00+08:00', notes: '巡检后补灌' },
  { id: 6, greenhouse_id: 8, decision_id: null, initiated_by_user_id: 2, trigger_source: 'rule', duration_minutes: 22, water_volume_m3: 1.9, started_at: '2026-04-03T09:05:00+08:00', completed_at: '2026-04-03T09:27:00+08:00', notes: '番茄棚低水分预警联动' },
  { id: 7, greenhouse_id: 11, decision_id: null, initiated_by_user_id: 1, trigger_source: 'manual', duration_minutes: 10, water_volume_m3: 0.7, started_at: '2026-04-03T09:40:00+08:00', completed_at: '2026-04-03T09:50:00+08:00', notes: '水培液循环校准' },
  { id: 8, greenhouse_id: 12, decision_id: null, initiated_by_user_id: 3, trigger_source: 'manual', duration_minutes: 14, water_volume_m3: 0.9, started_at: '2026-04-03T10:00:00+08:00', completed_at: '2026-04-03T10:14:00+08:00', notes: '草莓棚上午补液' },
];

export const controlLogs = [
  {
    id: 1,
    greenhouse_id: 2,
    user_id: 2,
    action_type: 'environment',
    target: '顶部通风',
    command: 'OPEN_VENT_TOP',
    status: 'success',
    requested_at: '2026-04-03T09:20:00+08:00',
    executed_at: '2026-04-03T09:20:08+08:00',
    result_message: '顶部通风窗已打开 35%',
    metadata_json: { opening_ratio: 35 },
  },
  {
    id: 2,
    greenhouse_id: 1,
    user_id: 2,
    action_type: 'irrigation',
    target: '滴灌阀组',
    command: 'CHECK_DRIP_LINE',
    status: 'queued',
    requested_at: '2026-04-03T10:25:00+08:00',
    executed_at: null,
    result_message: '等待人工确认执行',
    metadata_json: { source: 'dashboard-decision-center' },
  },
];

export const experiments = [
  {
    id: 1,
    park_id: 1,
    lead_user_id: 1,
    greenhouse_id: 1,
    name: '不同灌溉下限对番茄产量及WUE的影响',
    crop_name: '番茄',
    treatments: 4,
    replicates: 3,
    status: '进行中',
    start_date: '2026-03-01',
    ai_enabled: 0,
    summary: '围绕基质含水率下限进行滴灌策略比较，评估产量与水分利用效率。',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 2,
    park_id: 3,
    lead_user_id: 3,
    greenhouse_id: 3,
    name: '高架草莓夜间温光耦合调控试验',
    crop_name: '草莓',
    treatments: 3,
    replicates: 4,
    status: '已归档',
    start_date: '2025-11-15',
    ai_enabled: 0,
    summary: '验证夜间补光与微气候联动控制对果实膨大和糖度的影响。',
    created_at: NOW,
    updated_at: NOW,
  },
];

export const experimentDesigns = [
  {
    id: 1,
    experiment_id: 1,
    updated_by_user_id: 1,
    updated_at: NOW,
    layout_json: {
      blocks: [
        { block: 'A', treatment: 'T1 20%', replicates: ['A1', 'A2', 'A3'] },
        { block: 'B', treatment: 'T2 25%', replicates: ['B1', 'B2', 'B3'] },
        { block: 'C', treatment: 'T3 30%', replicates: ['C1', 'C2', 'C3'] },
        { block: 'D', treatment: 'T4 35%', replicates: ['D1', 'D2', 'D3'] },
      ],
    },
  },
  {
    id: 2,
    experiment_id: 2,
    updated_by_user_id: 3,
    updated_at: '2025-11-18T16:00:00+08:00',
    layout_json: {
      lanes: [
        { lane: 'L1', treatment: '夜温 16℃ + 无补光', plots: 4 },
        { lane: 'L2', treatment: '夜温 18℃ + 2h补光', plots: 4 },
        { lane: 'L3', treatment: '夜温 20℃ + 4h补光', plots: 4 },
      ],
    },
  },
];

export const phenotypeRecords = [
  { id: 1, experiment_id: 1, sample_code: 'T1-R1', trait_name: '单株产量', trait_value: 5.6, unit: 'kg', recorded_at: '2026-03-28T09:00:00+08:00', recorded_by_user_id: 1 },
  { id: 2, experiment_id: 1, sample_code: 'T2-R2', trait_name: 'WUE', trait_value: 31.2, unit: 'kg/m3', recorded_at: '2026-03-30T09:00:00+08:00', recorded_by_user_id: 1 },
  { id: 3, experiment_id: 1, sample_code: 'T4-R3', trait_name: '商品果率', trait_value: 92.5, unit: '%', recorded_at: '2026-04-01T09:00:00+08:00', recorded_by_user_id: 2 },
  { id: 4, experiment_id: 2, sample_code: 'L2-P3', trait_name: '可溶性固形物', trait_value: 10.8, unit: 'Brix', recorded_at: '2025-12-06T19:30:00+08:00', recorded_by_user_id: 3 },
];

export const irrigationDaily = [
  { id: 1, scope_type: 'park', scope_ref: 'park:1', record_date: '2026-03-28', water_usage_m3: 45.2 },
  { id: 2, scope_type: 'park', scope_ref: 'park:1', record_date: '2026-03-29', water_usage_m3: 52.8 },
  { id: 3, scope_type: 'park', scope_ref: 'park:1', record_date: '2026-03-30', water_usage_m3: 38.5 },
  { id: 4, scope_type: 'park', scope_ref: 'park:1', record_date: '2026-03-31', water_usage_m3: 65.1 },
  { id: 5, scope_type: 'park', scope_ref: 'park:1', record_date: '2026-04-01', water_usage_m3: 48 },
  { id: 6, scope_type: 'park', scope_ref: 'park:1', record_date: '2026-04-02', water_usage_m3: 55.4 },
  { id: 7, scope_type: 'park', scope_ref: 'park:1', record_date: '2026-04-03', water_usage_m3: 42.6 },
  { id: 8, scope_type: 'greenhouse', scope_ref: 'greenhouse:1', record_date: '2026-03-28', water_usage_m3: 6.8 },
  { id: 9, scope_type: 'greenhouse', scope_ref: 'greenhouse:1', record_date: '2026-03-29', water_usage_m3: 7.2 },
  { id: 10, scope_type: 'greenhouse', scope_ref: 'greenhouse:1', record_date: '2026-03-30', water_usage_m3: 5.9 },
  { id: 11, scope_type: 'greenhouse', scope_ref: 'greenhouse:1', record_date: '2026-03-31', water_usage_m3: 8.1 },
  { id: 12, scope_type: 'greenhouse', scope_ref: 'greenhouse:1', record_date: '2026-04-01', water_usage_m3: 6.4 },
  { id: 13, scope_type: 'greenhouse', scope_ref: 'greenhouse:1', record_date: '2026-04-02', water_usage_m3: 7.5 },
  { id: 14, scope_type: 'greenhouse', scope_ref: 'greenhouse:1', record_date: '2026-04-03', water_usage_m3: 6.1 },
];

export const efficiencySnapshots = [
  {
    id: 1,
    scope_type: 'park',
    scope_ref: 'park:1',
    metric_key: 'wue',
    metric_label: '水分利用率 (WUE)',
    score_label: '优秀',
    score_percent: 85,
    record_month: '2026-04',
    insight_text: '本月A区番茄夜温控制略有偏差，导致环境达标率下降，建议调整夜间通风策略。',
    created_at: NOW,
  },
  {
    id: 2,
    scope_type: 'park',
    scope_ref: 'park:1',
    metric_key: 'pfp',
    metric_label: '肥料偏生产力 (PFP)',
    score_label: '良好',
    score_percent: 72,
    record_month: '2026-04',
    insight_text: '本月A区番茄夜温控制略有偏差，导致环境达标率下降，建议调整夜间通风策略。',
    created_at: NOW,
  },
  {
    id: 3,
    scope_type: 'park',
    scope_ref: 'park:1',
    metric_key: 'env_compliance',
    metric_label: '环境达标率 (温度/湿度)',
    score_label: '需改善',
    score_percent: 58,
    record_month: '2026-04',
    insight_text: '本月A区番茄夜温控制略有偏差，导致环境达标率下降，建议调整夜间通风策略。',
    created_at: NOW,
  },
  {
    id: 4,
    scope_type: 'greenhouse',
    scope_ref: 'greenhouse:1',
    metric_key: 'wue',
    metric_label: '水分利用率 (WUE)',
    score_label: '良好',
    score_percent: 78,
    record_month: '2026-04',
    insight_text: 'A区番茄棚夜间湿度偏高，建议联动除湿策略。',
    created_at: NOW,
  },
  {
    id: 5,
    scope_type: 'greenhouse',
    scope_ref: 'greenhouse:1',
    metric_key: 'pfp',
    metric_label: '肥料偏生产力 (PFP)',
    score_label: '良好',
    score_percent: 70,
    record_month: '2026-04',
    insight_text: 'A区番茄棚夜间湿度偏高，建议联动除湿策略。',
    created_at: NOW,
  },
  {
    id: 6,
    scope_type: 'greenhouse',
    scope_ref: 'greenhouse:1',
    metric_key: 'env_compliance',
    metric_label: '环境达标率 (温度/湿度)',
    score_label: '需改善',
    score_percent: 54,
    record_month: '2026-04',
    insight_text: 'A区番茄棚夜间湿度偏高，建议联动除湿策略。',
    created_at: NOW,
  },
];

export const systemRules = [
  {
    id: 1,
    code: 'env.temp.high_threshold',
    category: 'environment',
    name: '高温报警阈值',
    description: '棚内温度超过该阈值时触发环境报警。',
    value_type: 'number',
    numeric_value: 35,
    boolean_value: null,
    text_value: null,
    unit: '°C',
    comparison_operator: '>',
    duration_minutes: 0,
    action_mode: 'alert_only',
    enabled: 1,
    updated_by_user_id: 1,
    updated_at: NOW,
  },
  {
    id: 2,
    code: 'env.humidity.high_threshold',
    category: 'environment',
    name: '高湿报警阈值',
    description: '空气湿度超过该阈值时触发病害风险报警。',
    value_type: 'number',
    numeric_value: 85,
    boolean_value: null,
    text_value: null,
    unit: '%',
    comparison_operator: '>',
    duration_minutes: 0,
    action_mode: 'alert_only',
    enabled: 1,
    updated_by_user_id: 1,
    updated_at: NOW,
  },
  {
    id: 3,
    code: 'irrigation.low_moisture_auto_decision',
    category: 'irrigation',
    name: '基质含水率过低自动生成决策',
    description: '连续2小时低于阈值时自动向决策中心推送灌溉建议。',
    value_type: 'boolean',
    numeric_value: 25,
    boolean_value: 1,
    text_value: '基质含水率低于25%',
    unit: '%',
    comparison_operator: '<',
    duration_minutes: 120,
    action_mode: 'decision_push',
    enabled: 1,
    updated_by_user_id: 1,
    updated_at: NOW,
  },
  {
    id: 4,
    code: 'system.full_auto_unattended',
    category: 'system',
    name: '全自动无人值守模式',
    description: '系统生成决策后直接联动执行设备，跳过人工确认。',
    value_type: 'boolean',
    numeric_value: null,
    boolean_value: 0,
    text_value: null,
    unit: null,
    comparison_operator: null,
    duration_minutes: null,
    action_mode: 'auto_execute',
    enabled: 1,
    updated_by_user_id: 1,
    updated_at: NOW,
  },
  {
    id: 5,
    code: 'irrigation.ec.high_threshold',
    category: 'irrigation',
    name: '高 EC 阈值',
    description: '基质 EC 超过阈值时提示水肥风险。',
    value_type: 'number',
    numeric_value: 2.6,
    boolean_value: null,
    text_value: null,
    unit: 'mS/cm',
    comparison_operator: '>',
    duration_minutes: 0,
    action_mode: 'alert_only',
    enabled: 1,
    updated_by_user_id: 1,
    updated_at: NOW,
  },
  {
    id: 6,
    code: 'weather.linkage_enabled',
    category: 'weather',
    name: '天气联动校正',
    description: '结合未来天气和蒸散模型自动修正阈值与策略。',
    value_type: 'boolean',
    numeric_value: null,
    boolean_value: 1,
    text_value: null,
    unit: null,
    comparison_operator: null,
    duration_minutes: null,
    action_mode: 'threshold_adjust',
    enabled: 1,
    updated_by_user_id: 1,
    updated_at: NOW,
  },
  {
    id: 7,
    code: 'alert.severe_escalation',
    category: 'alert',
    name: '高风险自动升级',
    description: '高风险报警自动升级到负责人。',
    value_type: 'boolean',
    numeric_value: null,
    boolean_value: 1,
    text_value: null,
    unit: null,
    comparison_operator: null,
    duration_minutes: null,
    action_mode: 'force_notify',
    enabled: 1,
    updated_by_user_id: 1,
    updated_at: NOW,
  },
  {
    id: 8,
    code: 'alert.notify_levels',
    category: 'alert',
    name: '报警通知等级',
    description: '定义需要通知的报警等级。',
    value_type: 'text',
    numeric_value: null,
    boolean_value: null,
    text_value: '高,中',
    unit: null,
    comparison_operator: null,
    duration_minutes: null,
    action_mode: 'notify_filter',
    enabled: 1,
    updated_by_user_id: 1,
    updated_at: NOW,
  },
];

export const integrationServices = [
  {
    id: 1,
    code: 'iot-mqtt-gateway',
    name: '物联网 MQTT 网关',
    type: 'mqtt',
    endpoint: 'mqtt.agri-cloud.net:1883',
    status: 'connected',
    enabled: 1,
    response_time_ms: 9,
    last_heartbeat_at: '2026-04-03T10:25:00+08:00',
    config_json: {
      broker: 'mqtt.agri-cloud.net',
      port: 1883,
      topic_prefix: 'greenhouse/agri',
      credentialsVersion: 'v3',
    },
    updated_at: NOW,
  },
  {
    id: 2,
    code: 'weather-bureau-api',
    name: '气象局数据接口 (API)',
    type: 'api',
    endpoint: 'https://weather.agri-cloud.net/v1/forecast',
    status: 'stopped',
    enabled: 0,
    response_time_ms: null,
    last_heartbeat_at: null,
    config_json: {
      provider: 'National Weather Service',
      sync_window_days: 7,
      target_metric: 'ET0',
      credentialsVersion: 'v1',
    },
    updated_at: NOW,
  },
  {
    id: 3,
    code: 'research-sync-service',
    name: '科研数据同步服务',
    type: 'sync',
    endpoint: 'sync.smart-agri.local/research',
    status: 'connected',
    enabled: 1,
    response_time_ms: 23,
    last_heartbeat_at: '2026-04-03T09:58:00+08:00',
    config_json: {
      dataset: 'phenotype-and-experiment',
      mode: 'incremental',
      credentialsVersion: 'v2',
    },
    updated_at: NOW,
  },
];

export const notificationSettings = [
  {
    id: 1,
    in_app: 1,
    sms: 1,
    email: 0,
    wecom: 1,
    daily_report: 1,
    quiet_hours_enabled: 1,
    quiet_start: '22:00',
    quiet_end: '06:30',
    escalation_receiver: '李建国',
    report_frequency: '每日 18:00',
    last_test_channel: '应用内通知',
    updated_by_user_id: 1,
    updated_at: NOW,
  },
];

export const securitySettings = [
  {
    id: 1,
    retention_days: 180,
    backup_frequency: '每日 02:00',
    backup_compression: 1,
    mfa_required: 0,
    api_read_only_mode: 0,
    session_timeout: 60,
    auto_export_alerts: 1,
    token_version: 'token-v4-20260403',
    last_backup: '2026-04-03 02:00',
    updated_by_user_id: 1,
    updated_at: NOW,
  },
];

export const operationsSettings = [
  {
    id: 1,
    maintenance_mode: 0,
    maintenance_window: '周日 23:00 - 23:30',
    auto_health_check: 1,
    updated_by_user_id: 1,
    updated_at: NOW,
  },
];

export const configSnapshots = [
  {
    id: 1,
    name: '系统初始基线',
    status: '基线',
    payload_json: {
      ruleSettings: {
        highTemp: 35,
        highHumidity: 85,
        lowSoilMoisture: 25,
        highEc: 2.6,
        autoDecision: true,
        unattendedMode: false,
        weatherLinkage: true,
        severeEscalation: true,
        anomalyWindow: 120,
        notifyLevels: ['高', '中'],
      },
      notificationSettings: {
        inApp: true,
        sms: true,
        email: false,
        wecom: true,
        dailyReport: true,
        quietHoursEnabled: true,
        quietStart: '22:00',
        quietEnd: '06:30',
        escalationReceiver: '李建国',
        reportFrequency: '每日 18:00',
        lastTestChannel: '应用内通知',
      },
      integrationServices: [
        { code: 'iot-mqtt-gateway', enabled: true, status: 'connected', latency: '9ms', credentialsVersion: 'v3' },
        { code: 'weather-bureau-api', enabled: false, status: 'stopped', latency: '--', credentialsVersion: 'v1' },
        { code: 'research-sync-service', enabled: true, status: 'connected', latency: '23ms', credentialsVersion: 'v2' },
      ],
      securitySettings: {
        retentionDays: 180,
        backupFrequency: '每日 02:00',
        backupCompression: true,
        mfaRequired: false,
        apiReadOnlyMode: false,
        sessionTimeout: 60,
        autoExportAlerts: true,
        tokenVersion: 'token-v4-20260403',
      },
      opsSettings: {
        maintenanceMode: false,
        maintenanceWindow: '周日 23:00 - 23:30',
        autoHealthCheck: true,
      },
    },
    created_by_user_id: 1,
    created_at: '2026-04-03T08:00:00+08:00',
  },
  {
    id: 2,
    name: '科研保守模板',
    status: '推荐',
    payload_json: {
      ruleSettings: {
        highTemp: 33,
        highHumidity: 82,
        lowSoilMoisture: 28,
        highEc: 2.3,
        autoDecision: true,
        unattendedMode: false,
        weatherLinkage: true,
        severeEscalation: true,
        anomalyWindow: 90,
        notifyLevels: ['高', '中'],
      },
      notificationSettings: {
        inApp: true,
        sms: true,
        email: true,
        wecom: true,
        dailyReport: true,
        quietHoursEnabled: true,
        quietStart: '22:00',
        quietEnd: '06:30',
        escalationReceiver: '张秫瑄',
        reportFrequency: '每日 08:00',
        lastTestChannel: '邮件摘要',
      },
      integrationServices: [
        { code: 'iot-mqtt-gateway', enabled: true, status: 'connected', latency: '9ms', credentialsVersion: 'v3' },
        { code: 'weather-bureau-api', enabled: false, status: 'stopped', latency: '--', credentialsVersion: 'v1' },
        { code: 'research-sync-service', enabled: true, status: 'connected', latency: '23ms', credentialsVersion: 'v2' },
      ],
      securitySettings: {
        retentionDays: 180,
        backupFrequency: '每日 02:00',
        backupCompression: true,
        mfaRequired: true,
        apiReadOnlyMode: false,
        sessionTimeout: 45,
        autoExportAlerts: true,
        tokenVersion: 'token-v4-20260403',
      },
      opsSettings: {
        maintenanceMode: false,
        maintenanceWindow: '周日 23:00 - 23:30',
        autoHealthCheck: true,
      },
    },
    created_by_user_id: 1,
    created_at: '2026-04-02T18:30:00+08:00',
  },
];

export const activityLogs = [
  {
    id: 1,
    user_id: 1,
    entity_type: 'experiment',
    entity_id: 1,
    action: 'create',
    summary: '创建番茄灌溉阈值试验项目',
    details_json: { source: 'research-page', name: '不同灌溉下限对番茄产量及WUE的影响' },
    occurred_at: '2026-03-01T09:00:00+08:00',
  },
  {
    id: 2,
    user_id: 2,
    entity_type: 'alert',
    entity_id: 4,
    action: 'resolve',
    summary: '处理 B区黄瓜棚温度过高报警',
    details_json: { method: 'ventilation-and-cooling' },
    occurred_at: '2026-04-02T14:48:00+08:00',
  },
  {
    id: 3,
    user_id: 3,
    entity_type: 'integration',
    entity_id: 2,
    action: 'toggle',
    summary: '关闭气象局数据接口',
    details_json: { enabled: false },
    occurred_at: '2026-04-03T08:30:00+08:00',
  },
  {
    id: 4,
    user_id: 1,
    entity_type: 'rule',
    entity_id: 3,
    action: 'update',
    summary: '更新低水分自动决策规则',
    details_json: { threshold: 25, duration_minutes: 120 },
    occurred_at: '2026-04-03T09:10:00+08:00',
  },
  {
    id: 5,
    user_id: 2,
    entity_type: 'control',
    entity_id: 1,
    action: 'execute',
    summary: '执行 B区黄瓜棚通风指令',
    details_json: { command: 'OPEN_VENT_TOP', status: 'success' },
    occurred_at: '2026-04-03T09:20:08+08:00',
  },
];
